version: '3.8'
services:
  db:
    image: postgres:13.2@sha256:5cfcfb0516ddd317109e2746a462b1dc398d152936640a2b69284629f48dc288
    env_file:
      - ./.env.example
    environment:
      POSTGRES_DB: ${SQL_DATABASE:-audit}
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - ${SQL_PORT:-5432}
    restart: on-failure
  web:
    build: 
      context: ./
    image: mobile_audit
    env_file:
      - ./.env.example
    entrypoint: [ '/web_entrypoint.sh' ]
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
    restart: on-failure
  nginx:
    image: nginx:1.19.7@sha256:f3693fe50d5b1df1ecd315d54813a77afd56b0245a404055a946574deb6b34fc
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - web
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.8.12-management@sha256:9d340b284990eb7f465616504f3fb058948ce58065997aa54d802aab0e8e60c2
    env_file:
      - ./.env.example
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - ./rabbitmq/logs/:/var/log/rabbitmq/
    expose:
      - "5672"
    depends_on:
      - web
    restart: on-failure
  worker:
    image: mobile_audit
    env_file:
      - ./.env.example
    entrypoint: [ '/worker_entrypoint.sh' ]
    volumes:
      - .:/app
    links:
      - rabbitmq
      - web
    depends_on:
      - rabbitmq
    restart: on-failure
volumes:
  db-data: